name    'bschmidt-puppetclient'
version '0.1.1'
author  'Bernhard Schmidt'
license 'Apache License, Version 2.0'
summary 'Manages a Puppet client installation'
description 'Manage a Puppet client.'
project_page 'https://github.com/bernhardschmidt/puppetclient'

dependency 'puppetlabs/apt', '>=0.0.4'
dependency 'puppetlabs/stdlib', '>=3.0.0'
